FROM eclipse-temurin:21-alpine AS jre-build

# Create a custom Java runtime
RUN apk add binutils --no-cache
RUN $JAVA_HOME/bin/jlink \
        --add-modules java.se \
        --strip-debug \
        --no-man-pages \
        --no-header-files \
        --compress=2 \
        --output /javaruntime

# Our resulting Alpine-based image
FROM alpine:latest
ENV JAVA_HOME=/opt/java
ENV PATH "${JAVA_HOME}/bin:${PATH}"
COPY --from=jre-build /javaruntime $JAVA_HOME
