on:
  push:
    branches:
      - "main"
  schedule:
    # Runs every week
    - cron: '0 0 * * 0'

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          make build
        env:
          GIT_TAG: ${{ github.ref }}

      - name: Push Docker images
        run: |
          make push
        env:
          GIT_TAG: ${{ github.ref }}
