on:
  push:
    branches:
      - "main"
  schedule:
    # Runs every week
    - cron: '0 0 * * 0'

jobs:
  push-tools:
    name: jdk-build-tools
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          make build-jdk-build-tools

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
        
      - name: Push Docker image
        run: |
          make push-jdk-build-tools

  push-jre17-minimal-debian:
    name: jre17-minimal-debian
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          make build-jre17-minimal-debian

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
        
      - name: Push Docker image
        run: |
          make push-jre17-minimal-debian

  push-jre17-minimal-alpine:
    name: jre17-minimal-alpine
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          make build-jre17-minimal-alpine

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
        
      - name: Push Docker image
        run: |
          make push-jre17-minimal-alpine
